require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 10

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**'