require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

# We disable this to allow automatic releases
Gemspec/RequireMFA:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Max: 100

Metrics/MethodLength:
  Max: 30

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 10

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**'