name: build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Build
      run: gem build paypro.gemspec

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Lint
      run: bundle install && bundle exec rubocop

  test:
    name: Test (${{ matrix.ruby-version }})
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', 3.1, 3.2]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Test
        run: bundle install && bundle exec rspec
